---
title: "psy 4802 quiz 1"
author: "Cali Keller"
date: "2025-10-13"
output: html_document
---
---
title: "Quiz 1"
author: "Amanda Mae Woodward"
date: "2025-10-07"
output: html_document
---

This quiz will cover everything we've covered in foundations of R assignments.

1. Open the tidyverse library.
2. Open the starwars dataset.
3. Create a subset of data that contains only the humans from the starwars franchise.
4. In this subset of data, who is the tallest character? 
5. In this subset of data, print the information about the character in the third row. 
6. In the full starwars dataset, calculate the average mass for the masculine characters. 
7. Create a dataset that contains only the characters and the films that they appeared in from the full dataset. 
8. Create a new column in the starwars dataset that contains a "ranking" of all characters (Note: you don't have to actually rank them. Just fill the column in with the numbers 1-87)
9. Create a subset of data for the characters from Naboo. How many characters are from Naboo? 
10. How many droids are in the full dataset? 